In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_rating = pd.read_csv("ratings.csv")
df_whiskey = pd.read_csv("whiskey.csv")

In [3]:
df_rating

       UID  whiskey  Liking - DEPENDANT VARIABLE
0     1101      873                            9
1     1101      462                            4
2     1101      423                            3
3     1101      324                            1
4     1101      754                            3
...    ...      ...                          ...
4683  1475      378                            3
4684  1475      617                            2
4685  1475      982                            6
4686  1475      948                            2
4687  1475      355                            4

[4688 rows x 3 columns]

In [4]:
df_whiskey

    Whiskey  Harshness  Sweetness  Nutiness  Smokiness  Creaminess
0       110       6.93       5.61      4.30       6.44        6.18
1       121       7.79       5.45      4.67       6.34        6.84
2       135       5.50       6.77      5.92       4.91        4.15
3       171       6.90       5.36      4.51       5.23        6.19
4       231       5.25       7.02      6.66       6.33        3.69
5       248       5.87       6.31      5.52       4.48        5.10
6       274       5.53       6.38      5.57       5.58        4.38
7       299       5.16       5.27      4.29       3.36        4.77
8       305       5.98       6.80      5.82       6.33        4.61
9       324       7.20       7.26      6.83       6.22        4.82
10      355       7.62       6.01      5.26       5.71        6.06
11      378       5.53       5.84      4.67       5.46        4.68
12      406       7.59       4.84      4.02       6.48        7.52
13      423       6.36       7.40      6.28       5.66        4.00
14      447       7.44       4.93      4.28       5.89        7.11
15      462       6.80       5.77      5.21       4.63        5.27
16      494       4.42       6.03      5.61       3.65        3.65
17      524       6.45       7.42      7.13       6.99        3.57
18      579       4.47       7.10      6.31       6.32        3.16
19      617       6.58       6.88      6.43       6.42        4.33
20      623       4.86       6.96      6.35       6.24        3.27
21      649       6.51       5.83      5.25       4.84        5.41
22      663       7.37       5.32      4.59       5.45        6.71
23      684       7.67       5.13      3.88       6.30        7.32
24      724       6.74       5.00      4.23       5.83        6.92
25      731       5.49       6.17      5.27       5.13        4.56
26      781       4.79       6.53      6.07       4.22        3.53
27      798       7.22       6.51      5.93       5.42        5.61
28      814       6.35       4.80      4.25       5.34        6.14
29      827       6.88       7.04      6.56       5.22        5.15
30      839       6.46       6.26      5.11       5.48        5.67
31      873       6.62       6.21      4.95       5.30        5.98
32      927       6.69       7.14      6.55       5.67        4.55
33      948       5.63       4.03      3.20       4.38        6.62
34      982       6.17       6.25      5.26       4.98        5.65

In [5]:
df_rating["whiskey"] = df_whiskey["Whiskey"].astype(int)

KeyError: 'whiskey'